# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeAndGrossRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('dgr_mark_year', models.CharField(max_length=20)),
                ('dgr_degree', models.CharField(max_length=20)),
                ('dgr_gross', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('dt_name', models.CharField(max_length=200)),
                ('talk_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('real_name', models.CharField(max_length=200)),
                ('work_no', models.CharField(max_length=20)),
                ('talk_user_id', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.SmallIntegerField(choices=[(1, 'boy'), (2, 'girl')], default=1)),
                ('birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('emergent_name', models.CharField(blank=True, max_length=20)),
                ('emergent_mobile', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('last_year_degree', models.CharField(blank=True, max_length=20)),
                ('last_year_gross', models.CharField(blank=True, max_length=20)),
                ('emp_related_dt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('lr_title', models.CharField(max_length=200)),
                ('lr_related_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PositionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('pr_title', models.CharField(max_length=200)),
                ('pr_related_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('tr_title', models.CharField(max_length=200)),
                ('tr_content', models.TextField()),
                ('tr_related_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
