# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('budget', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseBaseInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('identifier', models.CharField(max_length=20)),
                ('case_title', models.CharField(max_length=200)),
                ('contract_no', models.CharField(blank=True, max_length=40, null=True)),
                ('pay_type', models.CharField(blank=True, max_length=200, null=True)),
                ('current_budget', models.FloatField(blank=True, null=True)),
                ('contract_total', models.FloatField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('case_address', models.CharField(max_length=256)),
                ('case_deadline', models.DateField()),
                ('milestone', models.SmallIntegerField(choices=[(0, 'closed'), (1, 'set up the project'), (2, 'bid the project'), (3, 'sign contract'), (4, 'start implementation'), (5, 'check and accept'), (6, 'services ')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('budget', models.FloatField()),
                ('budget_type', models.SmallIntegerField(choices=[(0, 'miscellaneous expenses'), (1, 'selling expenses'), (2, 'implementation costs')], default=0)),
                ('approved', models.BooleanField(default=False)),
                ('cost_of_used', models.FloatField()),
                ('open_ratio', models.FloatField()),
                ('warning_tag', models.BooleanField(default=False)),
                ('warning_level', models.FloatField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseBaseInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('total', models.FloatField()),
                ('cost_type', models.SmallIntegerField(choices=[(1, 'catering expense'), (2, 'traffic expense (except air ticket)'), (3, 'air ticket expense'), (4, 'hotel expense'), (5, 'miscellaneous expenses')], default=5)),
                ('occurrence_time', models.DateField()),
                ('approve_sequence', models.CharField(max_length=500)),
                ('current_approve', models.CharField(max_length=100)),
                ('approve_record', models.TextField()),
                ('is_fin', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseBaseInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('to_pay_total', models.FloatField()),
                ('to_pay_ratio', models.FloatField()),
                ('to_pay_times', models.SmallIntegerField(choices=[(1, 'first payment'), (2, 'second payment'), (3, 'third payment'), (4, 'forth payment'), (5, 'fifth payment')], default=1)),
                ('to_pay_date', models.DateField()),
                ('pay_total', models.FloatField()),
                ('pay_time', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseBaseInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('position', models.SmallIntegerField(choices=[(1, 'Development Manager'), (2, 'Project Manager'), (3, 'Designer'), (4, 'Developer')], default=4)),
                ('ratio', models.SmallIntegerField(choices=[(1, '0.5'), (2, '0.75'), (3, '1')], default=1)),
                ('enter_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('workload', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseBaseInfo')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=40)),
                ('update_user', models.CharField(max_length=40)),
                ('remark', models.TextField()),
                ('identifier', models.CharField(max_length=20)),
                ('customer_title', models.CharField(max_length=200)),
                ('financial_account', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_account', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('financial_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casebaseinfo',
            name='customer_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Customer'),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseBaseInfo'),
        ),
    ]
